services:
  api:
    build: .
    image: alessandro133/rest-service-api
    networks:
      - rest-network      
    ports:
      - "$PORT:$PORT"
    restart: on-failure
    depends_on:
      - database
    environment:
      - POSTGRES_HOST=database
    volumes:
      - ./src:/usr/app/src
    command: ["npm", "run", "start:dev"]

  database:
    build: ./database
    image: alessandro133/rest-service-database
    networks:
      - rest-network      
    ports:
      - "$POSTGRES_PORT:$POSTGRES_PORT"   
    restart: on-failure 
    volumes:
      - ./database/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    command: ["postgres", "-c", "logging_collector=on", "-c", "log_directory=.", "-c", "log_filename=postgresql.log", "-c", "log_statement=all"]
networks:
  rest-network:
    driver: bridge

