services:
  api:
    build: .
    ports:
      - "$PORT:$PORT"
    restart: on-failure
    depends_on:
      - database
    environment:
      - POSTGRES_HOST=database
    volumes:
      - ./src:/usr/app/src
    command: ["npm", "run", "start:dev"]

  database:
    build: ./database
    ports:
      - "$POSTGRES_PORT:$POSTGRES_PORT"   
    restart: on-failure 
    volumes:
      - ./database/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
